server:
  port: 8129
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
spring:
  application:
    name: hlhdidi-zull
zuul:
#  SendErrorFilter:
#    error:
#      disable: true
  routes:
    api-a:
      path: /api-a/**
      serviceId: hlhdidi-eureka-client
      customSensitiveHeaders: true
      sensitiveHeaders: ''
    api-c:
      path: /api-b/**
      serviceId: hlhdidi-hystrix-server
  add-host-header: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 210000
ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 50000