server:
  port: 9012
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
spring:
  application:
    name: hlhdidi-feign
hlhdidi-eureka-client:
  ribbon:
    ConnectTimeout: 2000
    ReadTimeout: 2000
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 1
feign:
  hystrix:
    enabled: true

