spring:
  application:
    name: spring-cloud-stream-receiver
  cloud:
    stream:
      bindings:
        xyy-hlhdidi-exchange:
          group: myxyy
          destination: thisxyy
          consumer:
            partitioned: true
      instance-count: 2
      instance-index: 1


server:
  port: 8082